-- Inserts 50 rows into the 'Categories' table with specified Id, Name, and Description values.
INSERT INTO [dbo].[Categories] ([Id], [Name], [Description])
VALUES
    (1, 'Electronics', 'Electronic gadgets and devices'),
    (2, 'Clothing', 'Apparel and accessories'),
    (3, 'Books', 'Printed books and ebooks'),
    (4, 'Home Goods', 'Furniture, decor, and household items'),
    (5, 'Food', 'Groceries and snacks'),
    (6, 'Toys', 'Children\s toys and games'),
    (7, 'Sports', 'Sports equipment and apparel'),
    (8, 'Beauty', 'Cosmetics and personal care products'),
    (9, 'Health', 'Health and wellness products'),
    (10, 'Technology', 'Computers, software, and peripherals'),
    (11, 'Automotive', 'Car parts and accessories'),
    (12, 'Jewelry', 'Watches, rings, necklaces, and bracelets'),
    (13, 'Music', 'CDs, vinyl records, and digital music'),
    (14, 'Movies', 'DVDs, Blu-rays, and streaming services'),
    (15, 'Art', 'Paintings, sculptures, and art supplies'),
    (16, 'Gardening', 'Plants, seeds, and gardening tools'),
    (17, 'Pets', 'Pet food, toys, and accessories'),
    (18, 'Travel', 'Luggage, travel accessories, and tour packages'),
    (19, 'Office Supplies', 'Pens, paper, and office equipment'),
    (20, 'Kitchenware', 'Cookware, utensils, and tableware'),
    (21, 'Furniture', 'Sofas, chairs, tables, and beds'),
    (22, 'Electronics Accessories', 'Phone cases, chargers, and headphones'),
    (23, 'Shoes', 'Sneakers, boots, and sandals'),
    (24, 'Bags', 'Backpacks, purses, and briefcases'),
    (25, 'Stationery', 'Notebooks, pens, and pencils'),
    (26, 'Games', 'Board games, video games, and card games'),
    (27, 'Outdoor Gear', 'Camping gear, hiking gear, and outdoor clothing'),
    (28, 'Musical Instruments', 'Guitars, pianos, and drums'),
    (29, 'Books & Magazines', 'Fiction, non-fiction, and magazines'),
    (30, 'Home Decor', 'Pillows, curtains, and rugs'),
    (31, 'Tools', 'Hand tools and power tools'),
    (32, 'Hardware', 'Nuts, bolts, and screws'),
    (33, 'Paint', 'Paint and painting supplies'),
    (34, 'Lighting', 'Lamps, light fixtures, and bulbs'),
    (35, 'Appliances', 'Refrigerators, stoves, and washing machines'),
    (36, 'Baby Products', 'Diapers, baby formula, and strollers'),
    (37, 'Senior Care', 'Medical supplies and assistive devices'),
    (38, 'Green Products', 'Eco-friendly and sustainable products'),
    (39, 'Vintage & Collectibles', 'Antique and vintage items'),
    (40, 'Educational Supplies', 'Textbooks, workbooks, and school supplies'),
    (41, 'Party Supplies', 'Balloons, party favors, and decorations'),
    (42, 'Gifts', 'Gift cards, gift baskets, and personalized gifts'),
    (43, 'Software', 'Computer software and applications'),
    (44, 'Digital Products', 'Ebooks, music downloads, and online courses'),
    (45, 'Services', 'Cleaning services'),
    (46, 'Financial Products', 'Insurance, loans, and investment products'),
    (47, 'Real Estate', 'Houses, apartments, and commercial properties'),
    (48, 'Automotive Services', 'Car washes, oil changes, and tire repair'),
    (49, 'Health & Fitness', 'Gym membership'),
    (50, 'Legal Services', 'Legal advice and representation');