-- Inserts 50 rows into the 'Products' table with specified Id, Name, Description, CategoryId, and Price values.
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [ProductCategoryId], [Price])
VALUES
    (1, 'Smartphone', 'Latest flagship smartphone', 1, 800),
    (2, 'Laptop', 'High-performance laptop', 1, 1200),
    (3, 'Tablet', 'Versatile tablet for work and play', 1, 400),
    (4, 'Headphones', 'Noise-cancelling headphones', 1, 200),
    (5, 'Smartwatch', 'Fitness tracker and smartwatch', 1, 300),
    (6, 'T-Shirt', 'Cotton t-shirt', 2, 20),
    (7, 'Jeans', 'Denim jeans', 2, 50),
    (8, 'Dress', 'Elegant dress', 2, 100),
    (9, 'Sneakers', 'Comfortable sneakers', 2, 80),
    (10, 'Jacket', 'Warm winter jacket', 2, 150),
    (11, 'Novel', 'Bestselling novel', 3, 20),
    (12, 'Textbook', 'Academic textbook', 3, 50),
    (13, 'Cookbook', 'Recipe book', 3, 30),
    (14, 'Comic Book', 'Superhero comic book', 3, 15),
    (15, 'Art Book', 'Coffee table art book', 3, 40),
    (16, 'Sofa', 'Comfortable sofa', 4, 500),
    (17, 'Dining Table', 'Wooden dining table', 4, 300),
    (18, 'Bed Frame', 'Metal bed frame', 4, 200),
    (19, 'Rug', 'Woolen rug', 4, 100),
    (20, 'Curtains', 'Window curtains', 4, 80),
    (21, 'Milk', 'Dairy milk', 5, 2),
    (22, 'Bread', 'Loaf of bread', 5, 3),
    (23, 'Eggs', 'Dozen eggs', 5, 2),
    (24, 'Cheese', 'Block of cheese', 5, 5),
    (25, 'Fruit', 'Mixed fruit', 5, 4),
    (26, 'Toy Car', 'Remote-controlled car', 6, 30),
    (27, 'Doll', 'Fashion doll', 6, 25),
    (28, 'Board Game', 'Family board game', 6, 20),
    (29, 'Puzzle', 'Jigsaw puzzle', 6, 15),
    (30, 'Lego Set', 'Building block set', 6, 40),
    (31, 'Football', 'Soccer ball', 7, 20),
    (32, 'Basketball', 'Basketball', 7, 25),
    (33, 'Tennis Racket', 'Tennis racket', 7, 50),
    (34, 'Running Shoes', 'Athletic running shoes', 7, 80),
    (35, 'Yoga Mat', 'Yoga mat', 7, 20),
    (36, 'Lipstick', 'Lip color', 8, 15),
    (37, 'Eyeliner', 'Eye liner', 8, 10),
    (38, 'Face Cream', 'Moisturizing cream', 8, 25),
    (39, 'Perfume', 'Fragrance', 8, 50),
    (40, 'Shampoo', 'Hair shampoo', 8, 10),
    (41, 'Vitamins', 'Vitamin supplements', 9, 20),
    (42, 'Protein Powder', 'Muscle-building powder', 9, 30),
    (43, 'Yoga Mat', 'Yoga mat', 9, 20),
    (44, 'Fitness Tracker', 'Wristband fitness tracker', 9, 50),
    (45, 'Meditation App', 'Mindfulness app', 9, 10),
    (46, 'Laptop', 'Gaming laptop', 10, 1500),
    (47, 'Smartphone', 'Budget smartphone', 10, 200),
    (48, 'Tablet', 'Tablet for kids', 10, 250),
    (49, 'Headphones', 'Wireless headphones', 10, 150),
    (50, 'Smartwatch', 'Basic smartwatch', 10, 100);